### ISSUE TITLE
Default Settings

### ISSUE THREAD

**Issue by SivanMehta** [SivanMehta/allocate#28]
We need to know what default settings would be nice for the user. As of 11/18/2016, we currently only have work time preference and sleep times.

Additional work in this respect would first entail talking to stakeholders and figuring out what settings should only be taken once.  Off the top of my head this could include weekend preference, how to distribute the work (start early/late), and predefined empty blocks (prayer, exercise, naps, etc...)

Next would be to define how these are implemented in code, but can come after we clearly define these user settings.

**Comment by Mjafri** [comment]
After talking to several potential end users, I found that almost everyone has different needs I think with the following settings we will be able to be flexible enough to cater to most users needs: 


- The option to set when are weekends (all countries actually don’t have Saturday Sunday Weekends)

- Ability to  set “break” (afternoon nap, prayer, church etc) times separately for weekends and
   weekdays (with an option to go into advance settings and setting each days time separately)

- Ability to  set sleep timing separately for weekends and weekdays (with an option to go into advance
   settings and setting each days sleep time separately)

- Alternatively this was suggested by a few users that they don’t sleep everyday on the same time 
   because their sleep depends on when their first class is so instead of having an option to set a fixed 
   time to sleep, how about having an option where they can enter how much they wanna sleep (will 
   explain this more in the meeting) 

- Having an option to select which calendar not to conflict with (Prof Raja’s suggestion where he had 
   his wife’s calendar but didn’t mind having conflicts with it)

**Comment by SivanMehta** [comment]
That's great! The next step is actually writing some code and implementing the suggestions that make sense. Checkout a new branch and start cracking!

I would start by modifying `models/setting.js`, along with the corresponding file in `test`, please let me know if you need any help.
